import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ApolloWrapper } from "../app/apolloWrapper";
import "./ui-library/vanilla.css";
import SideBar from "./components/sidebar/SideBar";
import { myFont } from "./font";
import { mainContent, structure } from "./general.css";
import ActivityBar from "./components/activityBar/ActivityBar";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ApolloWrapper>
        <Providers>
          <body className={inter.className}>
            <div className={structure}>
              <SideBar />
              <div className={mainContent}>{children}</div>
              <ActivityBar />
            </div>
          </body>
        </Providers>
      </ApolloWrapper>
    </html>
  );
}
